// <auto-generated />
using System;
using DES1_Control_Empleados.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DES1_Control_Empleados.Migrations
{
    [DbContext(typeof(ControlEmpleadosDBContext))]
    [Migration("20260723051402_SeedersData")]
    partial class SeedersData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DES1_Control_Empleados.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "DEP-RH",
                            Description = "Gestión de talento humano",
                            Name = "Recursos Humanos"
                        },
                        new
                        {
                            Id = 2,
                            Code = "DEP-TI",
                            Description = "Sistemas y desarrollo",
                            Name = "Tecnología"
                        },
                        new
                        {
                            Id = 3,
                            Code = "DEP-VEN",
                            Description = "Ventas y marketing",
                            Name = "Ventas"
                        });
                });

            modelBuilder.Entity("DES1_Control_Empleados.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(1985, 5, 20),
                            Code = "EMP-001",
                            HireDate = new DateTime(2010, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "John Doe",
                            Salary = 50000m
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(1990, 3, 10),
                            Code = "EMP-002",
                            HireDate = new DateTime(2015, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jane Smith",
                            Salary = 70000m
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateOnly(1982, 11, 22),
                            Code = "EMP-003",
                            HireDate = new DateTime(2012, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mark Johnson",
                            Salary = 55000m
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateOnly(1978, 7, 30),
                            Code = "EMP-004",
                            HireDate = new DateTime(2005, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Emily Davis",
                            Salary = 75000m
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateOnly(1995, 12, 5),
                            Code = "EMP-005",
                            HireDate = new DateTime(2020, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Michael Brown",
                            Salary = 60000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
